#!/usr/bin/perl

use strict;
use warnings;

use List::Util qw(any all min max sum);

my %map;

my $y = 0;

my $xmax;

while (<>) {
    chomp;
    my @r = split //;
    for my $x (0 .. $#r) {
        $map{"$y,$x"} = $r[$x] eq '@';
        $xmax = $x;
    }

    $y++;
}

my $ymax = $y-1;

my $count = 0;

my $changed = 1;

while ($changed) {
    $changed = 0;
    for my $y (0..$ymax) {
        for my $x (0..$xmax) {
            next if !$map{"$y,$x"};
            my $c = 0;
            for my $dy (-1..1) {
                for my $dx (-1..1) {
                    next if $dx==0 && $dy==0;
                    my $px = $x+$dx;
                    my $py = $y+$dy;
                    $c += $map{"$py,$px"}||0;
                }
            }
            if ($c < 4) {
                $map{"$y,$x"} = 0;
                $changed = 1;
                $count++;
            }
        }
    }
}

print "$count\n";
