#!/usr/bin/perl

use strict;
use warnings;

use List::Util qw(sum);

my %conn;

while (<>) {
    chomp;
    my ($from, @to) = split /:? /;
    $conn{$from} = \@to;
}

my %paths;

print "".(route(svr => 'fft') * route(fft => 'dac') * route(dac => 'out') || route(svr => 'dac') * route(dac => 'fft') * route(fft => 'out')), "\n";

sub route {
    my ($from, $to) = @_;
    return 1 if $from eq $to;
    if (!defined $paths{"$from,$to"}) {
        $paths{"$from,$to"} = sum map { route($_,$to) } @{ $conn{$from} };
    }
    return $paths{"$from,$to"};
}
