#!/usr/bin/perl

use strict;
use warnings;

my %map;

my $y = 0;
my $h = 0;
my $w = 0;
while (<>) {
    chomp;
    $map{$y++} = [split //];
    $w = length $_;
    $h = $y;
}

my $startx = 0;
$startx++ while $map{0}[$startx] ne 'S';

my $splits = 0;
my %t;
print dfs($startx, 0), "\n";

sub dfs {
    no warnings 'recursion';
    my ($x, $y) = @_;
    if (!$t{"$x,$y"}) {
        if ($map{$y}[$x] eq '^') {
            $t{"$x,$y"} = dfs($x-1,$y) + dfs($x+1,$y);
        } elsif ($y == $h-1) {
            $t{"$x,$y"} = 1;
        } else {
            $t{"$x,$y"} = dfs($x,$y+1);
        }
    }
    return $t{"$x,$y"};
}
